cov19

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -38,17 +38,31 @@ jobs:
       - name: Generate Coverage Report
         run: |
           php -d xdebug.mode=coverage -d xdebug.start_with_request=yes vendor/bin/phpunit --configuration phpunit.xml --coverage-clover build/logs/clover.xml
+          echo "Contents of build/logs directory:"
           ls -la build/logs
-          cat build/logs/clover.xml || echo "No coverage.xml found"
+          if [ -f build/logs/clover.xml ]; then
+            echo "Coverage report generated successfully."
+          else
+            echo "Coverage report not found."
+            exit 1
+          fi
 
       - name: Generate HTML Coverage Report
         run: |
           php -d xdebug.mode=coverage -d xdebug.start_with_request=yes vendor/bin/phpunit --configuration phpunit.xml --coverage-html build/coverage
+          echo "Contents of build/coverage directory:"
+          ls -la build/coverage
+          if [ -d build/coverage ]; then
+            echo "HTML Coverage report generated successfully."
+          else
+            echo "HTML Coverage report not found."
+            exit 1
+          fi
 
       - name: Upload coverage report artifact
         uses: actions/upload-artifact@v2
         with:
-          name: CoverageReport 
+          name: CoverageReport
           path: build/logs/clover.xml
 
       - name: Upload HTML Coverage Report
