h1

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -6,7 +6,7 @@ env:
 
 on:
   push:
-    branches: [ "main" ]
+    branches: ["main"]
   workflow_dispatch:
 
 jobs:
@@ -28,21 +28,68 @@ jobs:
         run: composer install
 
       - name: Create reports directory
-        run: mkdir -p features/bootstrap/reports
+        run: mkdir -p features/bootstrap/reports build/logs build/coverage coveragereport
 
-      - name: Give execute permission to Behat
-        run: chmod +x vendor/bin/behat
+      - name: Give execute permission to Behat and PHPUnit
+        run: |
+          chmod +x vendor/bin/behat
+          chmod +x vendor/bin/phpunit
 
       - name: Run Behat tests
         run: vendor/bin/behat --format=html --out=features/bootstrap/reports/index.html
+      
+      - name: Generate HTML Coverage Report
+        run: |
+          php -d xdebug.mode=coverage -d xdebug.start_with_request=yes vendor/bin/phpunit --configuration phpunit.xml --coverage-html build/coverage
+          echo "Contents of build/coverage directory:"
+          ls -la build/coverage
+          if [ -d build/coverage ]; then
+            echo "HTML Coverage report generated successfully."
+          else
+            echo "HTML Coverage report not found."
+            exit 1
+          fi
+
+      - name: Generate Clover Coverage Report
+        run: |
+          php -d xdebug.mode=coverage -d xdebug.start_with_request=yes vendor/bin/phpunit --configuration phpunit.xml --coverage-clover build/logs/clover.xml
+          echo "Contents of build/logs directory:"
+          ls -la build/logs
+          if [ -f build/logs/clover.xml ]; then
+            echo "Clover Coverage report generated successfully."
+          else
+            echo "Clover Coverage report not found."
+            exit 1
+          fi
+
+      - name: Install .NET Core SDK
+        uses: actions/setup-dotnet@v1
+        with:
+          dotnet-version: '8.x'
+
+      - name: Install ReportGenerator
+        run: dotnet tool install --global dotnet-reportgenerator-globaltool
+
+      - name: Generate Markdown Coverage Summary
+        run: |
+          ~/.dotnet/tools/reportgenerator -reports:build/logs/clover.xml -targetdir:coveragereport -reporttypes:MarkdownSummary;MarkdownSummaryGithub
+          echo "Contents of coveragereport directory:"
+          ls -la coveragereport
+          if [ -f coveragereport/Summary.md ]; then
+            echo "Markdown Summary report generated successfully."
+          else
+            echo "Markdown Summary report not found."
+            exit 1
+          fi
+
+      - name: Publish coverage in build summary
+        run: cat coveragereport/Summary.md >> $GITHUB_STEP_SUMMARY
+        shell: bash
 
       - name: Check Database Connection
         run: |
           sudo apt-get install -y mariadb-client
           mysql --host 161.132.49.95 --port 3306 --user=escobar --password=Upt2024 --execute="SHOW DATABASES;"
-
-      - name: Set Execute Permission for PHPUnit
-        run: chmod +x vendor/bin/phpunit
 
       - name: Run tests with coverage report
         env:
@@ -78,12 +125,6 @@ jobs:
           personal_token: ${{ secrets.PAT_TOKEN }}
           publish_branch: bddreporte
           publish_dir: features/bootstrap/reports
-
-      - name: Install ReportGenerator
-        run: dotnet tool install -g dotnet-reportgenerator-globaltool
-
-      - name: Generate Markdown Coverage Summary
-        run: ~/.dotnet/tools/reportgenerator -reports:build/coverage/clover.xml -targetdir:coveragereport -reporttypes:MarkdownSummary;MarkdownSummaryGithub
 
       - name: Upload Coverage Summary
         uses: actions/upload-artifact@v2
